apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: configtracker
  labels:
    app: configtracker
    component: backend
spec:
  selector:
    app: configtracker
    component: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
