# Generated by Django 6.1.1 on 2026-10-01 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('intent', 'Intent'), ('design', 'Design'), ('running', 'Running'), ('startup', 'Startup')], default='running', max_length=20)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_configurations', to='inventory.configuration')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_configurations', to='inventory.device')),
            ],
            options={
                'unique_together': {('device', 'configuration', 'state')},
            },
        ),
    ]
