apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: configtracker
  labels:
    app: configtracker
    component: postgres
data:
  POSTGRES_DB: "configtracker"
  POSTGRES_USER: "postgres"
  PGDATA: "/var/lib/postgresql/data/pgdata"
