apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: configtracker
  labels:
    app: configtracker
    component: postgres
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
