apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: configtracker
  labels:
    app: configtracker
    component: postgres
spec:
  selector:
    app: configtracker
    component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
